### ISSUE TITLE
Assignment #1  problem 3-1 관련 질문

### ISSUE THREAD

**Issue by Dryeyesyndrome** [snu-sf-class/pp202402#10]
안녕하세요.  problem 3-1에서 isPrime이 모든 long type input에 대해서 수행되어야 하는지 궁금합니다.
 제 코드로는 과제에서 주어진 3-1 test가 10초 이내로 수행되었으나 long 타입에서 가장 큰 소수라고 알고 있는 9223372036854775783L에 대해 test 해봤을때는 테스트가 끝나지 않아 질문 드립니다.

**Comment by Yeonwoo-Nam** [comment]
문제 3-1은 제공된 testcase인 `9142446473643264109L` 이하의 input값으로만 채점하도록 하겠습니다.

**Comment by Dryeyesyndrome** [comment]
넵, 답변 감사합니다!

**Comment by Yeonwoo-Nam** [comment]
인수의 제곱이 주어진 input보다 큰지 확인하는 과정에서 해당 제곱수가 long의 범위를 넘어가 overflow가 나는 경우 `9142446473643264109L`는 통과하되 `9223372036854775783L`은 무한루프에 걸릴 수 있습니다. 해결이 불가능한 문제는 아니지만 출제 측에서도 고려하지 못했던 부분이므로 제공된 testcase인 9142446473643264109L 이하의 input값으로만 채점하도록 하겠습니다. 혼란을 드려 죄송합니다.
