### ISSUE TITLE
mac에서 시험환경이 안열립니다

### ISSUE THREAD

**Issue by jamesgeun2** [snu-sf-class/pp202402#16]
![IMG_1210](https://github.com/user-attachments/assets/f96429c1-333c-41fa-9317-e93820b0d952)

web IDE를 열려고 버튼을 누르면 이 상태가 되는데, quit를 누르면 튕기고 cancel을 누르면 아무일도 일어나지 않습니다. 어떻게 해야하나요?

**Comment by Yeonwoo-Nam** [comment]
quit을 누르면 퇴장 비밀번호를 요구하나요? 

사용하시는 PC의 운영체제 버전, 설치하신 SEB 버전을 알려주세요. 
SEB 로그도 파일로 첨부해주시면 도움이 될 수도 있습니다. (윈도우에서는 C:\Users\유저이름\AppData\Local\SafeExamBrowser\Logs 에 있는데 mac에서의 경로는 내일 찾아보겠습니다.

**Comment by jwchoi-kr** [comment]
안녕하세요 저도 macOS에서 같은 이슈가 발생합니다.
OS ver : 15.0.1(24A348)
SEB ver : 3.3.3

위 화면에서 quit하여 종료했을 때의 로그도 첨부합니다.
[org.safeexambrowser.SafeExamBrowser 2024-10-21--20-15-08-657.log](https://github.com/user-attachments/files/17466579/org.safeexambrowser.SafeExamBrowser.2024-10-21--20-15-08-657.log)

**Comment by Yeonwoo-Nam** [comment]
현재 macOS에서 새로운 창을 띄우거나 창간 전환하는 기능이 제한되는 문제가 발생하고 있습니다. 
이 문제를 우회하는 방법으로, 주소창에 webIDE 주소를 입력하거나 readme.md에 미리 입력해둔 webIDE 주소를 클릭하여 같은 창 안에서 다른 주소로 넘어가는 방식이 있습니다. 구체적으로, 아래 방법을 시도해보시기를 바랍니다. 

1. SEB에 접속하지 않은 상태로, "http://gl.kinetc.net:20105/-/ide/project/2024-11111_pp2402_group/pp-assignment-0/edit/main/-/" 이 주소를 assignment 0의 readme.md 파일에 적어넣습니다. 
2. test001 파일을 통해 SEB에 접속하고 로그인합니다. Edit 버튼을 누르는 대신 미리 적어둔 주소 링크를 클릭합니다. 
3. 브라우저 내 뒤로가기/앞으로가기 버튼으로 레포 페이지와 sebIDE 페이지를 오갈 수 있습니다. webIDE에서 내용을 수정 후 commit하고, 레포 페이지에서 새로고침으로 수정사항이 반영되었는지 확인합니다.

혼란을 드려 죄송합니다.

**Comment by jamesgeun2** [comment]
에디터 주소로 접속하고 commit까지 정상적으로 작동합니다. 그런데 web ide 상에서 vscode처럼 extension이 없어서 scala코드가 제대로 안보입니다. 그리고 commit하는법 말고 콘솔을 통해 테스트 코드를 동작시킬 수 있는 방법도 궁금합니다.

**Comment by haan6** [comment]
@jamesgeun2 실제 시험에서는 metals extension을 사용해 코드를 작성하고 컴파일할 수 있는 coder 환경이 제공될 예정입니다. [실제 시험 시 유의사항](https://github.com/snu-sf-class/pp202402/blob/main/seb/seb.md#%EC%8B%A4%EC%A0%9C-%EC%8B%9C%ED%97%98-%EC%8B%9C-%EC%9C%A0%EC%9D%98%EC%82%AC%ED%95%AD)을 참고하시면 시험 중 코드 작성 및 제출 방법을 확인하실 수 있습니다.
