### ISSUE TITLE
assignment0 관련 문의드립니다,.

### ISSUE THREAD

**Issue by Criminal0627** [snu-sf-class/pp202402#17]
다름이 아니라 제가 이름을 적는 칸에 "김용범ㅅ"으로 오타가 난 상태에서 push를 하고 방금 알아차렸는데 지금 다시 push해도 괜찮을까요?

**Comment by Yeonwoo-Nam** [comment]
assignment0는 채점 대상이 아니므로 어떤 내용을 어떻게 push하셔도 무방합니다.
