### ISSUE TITLE
Assignment 2B `Array` 사용 범위 질문드립니다.

### ISSUE THREAD

**Issue by thisisWooyeol** [snu-sf-class/pp202402#18]
안녕하세요, 과제 2B 스펙에서는 다음과 같이 안내하고 있습니다. 

>  - Do not use the keyword `var`. Use `val` and `def` instead.
>   - Do not use any library functions or data structures like `List`, `Range` (`1 to n`, `1 until n` ...), `fold`, `map`, `reduce` or etc except for `Array`.
>  - If you want to use a data structure, create new one instead of using the library ones.
>  - You can only use tuples, `scala.annotation.tailrec`, and `scala.util.control.TailCalls._`, `Array` from the library.
>  - Do not use any looping syntax of Scala (`for`, `while`, `do-while`, `yield`, ...)

이때, `Array.from`, `Array.fill` 등의 함수도 사용 가능한지 궁금합니다.
감사합니다.

**Comment by Yeonwoo-Nam** [comment]
Assignment 2B에서 array에 대해 사용 가능한 기능은 `val x = A(3)`이나 `A(4) = 7` 같은 access와 reassign뿐이며 이 외에 다른 함수 사용시 0점 처리됩니다.

**Comment by thisisWooyeol** [comment]
확인 감사합니다.

**Comment by caelum02** [comment]
Array constructor는 사용가능 한가요?
예를 들면, Array(*xs), Array.ofDim[A](n) 과 같은 함수입니다.

**Comment by haan6** [comment]
네 constructor는 사용하셔도 됩니다.

**Comment by caelum02** [comment]
감사합니다!

**Comment by haan6** [comment]
constructor, 기본적인 접근(val x = A(3))과 할당 방법(A(4) = 7) 이외의 추가 기능은 허용하지 않고 있습니다. (#27 에 드린 답변과 같은 내용입니다.)
