### ISSUE TITLE
Assignment 2 관련 질문드립니다.

### ISSUE THREAD

**Issue by kohandy1902** [snu-sf-class/pp202402#19]
1. 2A-insert 함수에서 이미 있는 Key가 insert할 대상으로 들어오면 어떡해야 하나요? 
2. 2B에서 제가 다른 Array를 정의해서 사용해도 되나요?

감사합니다.

**Comment by Yeonwoo-Nam** [comment]
1. 통상적인 방식대로, 이미 있는 key에 대해서 insert함수는 input tree와 동일한 ouput tree를 내놓습니다. 
2. 정의 자체가 금지되지는 않습니다만, index가 주어진 access와 assign외의 함수는 사용하실 수 없습니다.
