### ISSUE TITLE
Mysuite.scala  테스트 코드 관련 질문

### ISSUE THREAD

**Issue by eteq100** [snu-sf-class/pp202402#2]
올라온 Scala 실행 가이드를 따라 vscode에 metals를 설치해 테스트 코드를 실행했습니다. 가이드에 따라 Mysuite.scala에 있는 초록색 버튼을 눌러 디버깅하려고 했는데 아래 사진과 같은 오류가 뜨며 작동이 되지 않습니다.

![스크린샷 2024-09-12 115425](https://github.com/user-attachments/assets/a355ead9-7e92-464f-bfa3-d1a153d791c8)

gpt에 오류에 대해 질문했을때는 launch json이 비어있어 발생하는 오류로 add configuration을 이용하라고 답이 나왔는데 사진에 있는 scala configuration을 넣어도 해결이 되지 않습니다

![스크린샷 2024-09-12 120127](https://github.com/user-attachments/assets/46d62b54-dd7a-4619-9bd6-8e2241e27929)

터미널에 sbt test를 작성했을때는 Mysuite.scala가 정상적으로 실행됩니다.

오류를 해결할 방법이 있을까요?

**Comment by haan6** [comment]
안녕하세요 저희 쪽 컴퓨터들에서는 실행에 문제가 없었어서 에러를 확인하는 데 조금 더 정보가 필요할 것 같습니다. 

1. 지금 화면 상으로는 Importing build가 매우 오랜 시간 동안 돌아가고 있는 것 같은데 `run`이나 `debug` 실행 전에 완료가 되었나요?
2. 화면 하단 상태바에 `Bloop 2` warning 표시가 떠 있는데 공유해주시면 확인하겠습니다.

**Comment by Dryeyesyndrome** [comment]
안녕하세요. 질문 남겨주신 분과 완전히 같은 상황인지는 모르겠으나 같은 문제를 겪고 있어 답글을 남깁니다. 
 1. build가 완료된 상태에서도 같은 문제가 발생했습니다. run은 실행되지만 debug나 test를 하려 하면 첫 사진과 같은 오류 문구가 뜨면서 수행되지 않습니다.
 2. 저는 다음과 같이 나타났습니다.
![스크린샷 2024-09-15 022646](https://github.com/user-attachments/assets/82ad2aad-572b-40f7-9190-ae5897ff05d2)

**Comment by haan6** [comment]
다음 내용을 `.vscode/launch.json` 파일에 추가하여 디버깅이 되는지 한 번 확인해주시면 감사하겠습니다. [Scala Metals issues](https://github.com/scalameta/metals/issues)에 비슷한 문제를 고친 사례가 없어서 정확한 해결책을 찾는데 시간이 걸리고 있는데, 계속 에러가 뜨면 다음 수업 시간 전후에 같이 문제를 해결해보면 좋겠습니다.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "scala",
      "request": "attach",
      "name": "Attach debugger",
      "buildTarget": "<name of current directory>-build",
      "hostName": "localhost",
      "port": 5005
    },
],
}
```

(두 학생의 경우 `buildTarget` property에 각각 `"pw202401-build"`와 `"test2-build"`를 쓰면 될 것 같습니다.)

**Comment by eteq100** [comment]
1.저도 build가 돌아가지 않는 상태에서 디버깅을 시도했으나 똑같은 에러가 발생했습니다
2.
![스크린샷 2024-09-15 220631](https://github.com/user-attachments/assets/37c8e1ea-2ad2-4e31-83f6-6d2d0516b7db)
![스크린샷 2024-09-15 220640](https://github.com/user-attachments/assets/ab476802-08cc-4b0a-9023-6dbe7dcde1b7)
3.알려주신 코드를 launch.json에 입력했으나 똑같은 오류가 발생했습니다
![스크린샷 2024-09-15 220814](https://github.com/user-attachments/assets/771ec3e3-385e-4417-8854-8efff422efa8)
![스크린샷 2024-09-15 220915](https://github.com/user-attachments/assets/98376114-1258-4ca7-8814-feaac67aa9c8)

**Comment by Dryeyesyndrome** [comment]
안녕하세요.
 1. launch.json 파일을 추가했을 때도 같은 문제가 발생했습니다.
 2. 허용목록에 OpenJDK Platform binary가 있습니다.
![화면 캡처 2024-09-18 154214](https://github.com/user-attachments/assets/964e5610-f4da-4d82-ad46-40259b20cbfa)

**Comment by eteq100** [comment]
저도 허용목록에 있습니다

**Comment by haan6** [comment]
@eteq100 @Dryeyesyndrome 오늘 수업 이후에 가능하시면 오프라인으로 같이 문제를 해결해보아도 좋을 것 같습니다.

**Comment by Dryeyesyndrome** [comment]
넵
