### ISSUE TITLE
시험 환경 문의드립니다.

### ISSUE THREAD

**Issue by kreatinj** [snu-sf-class/pp202402#21]
안녕하세요 시험 환경 관련해서 두 가지 문의드립니다

### 1

https://github.com/snu-sf-class/pp202402/blob/main/seb/seb.md
> 6. 좌하단의 버튼을 눌러 창을 전환하고, 원래 gitlab 페이지에서 아무 문장이나 복사합니다.

좌하단 버튼이 어느 것을 의미하는지 모르겠습니다. 좌상단 브라우저 뒤로가기로 gitlab 페이지 이동하면 충분한 것일까요?

### 2

그리고 extension 조회가 안되는데 시험에서는 metals 사용이 불가한 것일까요?

**Comment by Yeonwoo-Nam** [comment]
1. 좌하단의 seb로고를 누르면 창 전환이 됩니다. mac의 경우 창 전환이 안 될 수 있는데, 뒤로가기를 사용해 gitlab페이지로 돌아갈 수 있다면 문제 없습니다.

2. 실제 시험에서는 metal extention과 함께 코드를 작성/컴파일/테스트할 수 있는 coder 환경이 제공될 예정입니다.
