### ISSUE TITLE
Assignment 2 마감기한

### ISSUE THREAD

**Issue by chriswon421** [snu-sf-class/pp202402#25]
2024/11/04 23:59:59 KST가 마감기한이라고 되어 있었습니다.
지금 gitlab에서 확인해보니 Archived project에 들어가 있습니다.
아직 commit하지 않아서 과제 제출하지 못한 상황이라 한번 확인 부탁드립니다. 감사합니다.

**Comment by haan6** [comment]
안녕하세요, 방금 모든 학생의 과제가 archive 된 것을 확인하여 다시 unarchive하였습니다. 한 번 확인해주시면 감사하겠습니다. 혼선을 드려 죄송합니다.

**Comment by yblee2001** [comment]
안녕하세요, 현시각 (11월 4일 02:10) 기준 아직 unarchive 되지 않은 상태인 것 같습니다. 혹시 다시 확인해주실 수 있을까요? 감사합니다.

**Comment by haan6** [comment]
안녕하세요, 과제 서버의 이상으로 unarchive된 레포들이 다시 archive되는 것 같습니다. 과제 마감기한은 11월 5일 23:59:59 KST로 연장하고 월요일 중으로 문제를 해결하여 다시 공지하겠습니다.

**Comment by haan6** [comment]
레포들을 모두 unarchive하였습니다.
