### ISSUE TITLE
Assignment #0

### ISSUE THREAD

**Issue by haan6** [snu-sf-class/pp202402#3]
Assignment #0 has been released. Instructions on how to complete your assignment have been sent to your ~`@snu.ac.kr` email address~ email address registered on ETL. Please check the `README.md` file in the repository for more information about the assignment.

**Comment by Criminal0627** [comment]
안녕하세요 조교님 컴퓨터공학부 21학번 김용범 학생입니다. 다름이 아니라 제게 메일이 오지 않은 것 같습니다. 확인해주시면 감사하겠습니다. 계정은 kybs0627@snu.ac.kr 입니다.

**Comment by GyubinKimProg** [comment]
저도 메일이 오지 않은 것 같습니다. 자유전공학부 20학번 김규빈 (2020-11726)이고 메일 계정은 kebinxyz@snu.ac.kr입니다.

**Comment by imjskim** [comment]
저도 메일을 못 받았습니다. 저는 컴퓨터공학부 2023-14694 김정수이고 메일 주소는 imjskim@snu.ac.kr입니다

**Comment by KyungWonCho** [comment]
저도 메일을 못받았습니다. 컴퓨터공학부 20학번 조경원 (2020-16655)이고 메일 주소는 cscandkswon@snu.ac.kr입니다.

**Comment by hometogo4ever** [comment]
안녕하세요 조교님. 제가 초대 메일이 스팸 메일함에 가있는 줄 모르고 있다가 뒤늦게 메일을 받았는데, Confirmation token is invalid라는 에러메세지가 뜨게 되어 아무래도 만료된듯 합니다. 혹시 다시 한번 메일을 받을 수 있을까요? 컴퓨터공학부 2023-15725 곽민서이고 메일 주소는 hometogo0625@snu.ac.kr 입니다.

**Comment by aedaqr** [comment]
저도 메일을 늦게 확인해서 Confirmation token is invalid라는 에러 메세지가 뜹니다. 메일을 다시 받을 수 있을까요? 자유전공학부 2023-15409 조영준이고 메일 주소는 gregory89@snu.ac.kr입니다.

**Comment by Yeonwoo-Nam** [comment]
위 두 학생 모두 메일 재전송했습니다. 접속 가능 여부 확인 바랍니다.

**Comment by imanoony** [comment]
안녕하세요 조교님. 컴퓨터공학부 23학번 최아윤입니다. 저 역시 메일이 스팸함에 가 있어 늦게 확인했습니다. 메일을 다시 받을 수 있을까요? 메일 주소는 teetee0000@snu.ac.kr입니다. 감사합니다.

**Comment by haan6** [comment]
지금까지 댓글을 달아준 학생들에게 메일을 재전송하였습니다. 접속 가능한지 확인 바랍니다.
