### ISSUE TITLE
[Assignment 3A] Input의 범위 관련 질문 드립니다.

### ISSUE THREAD

**Issue by caelum02** [snu-sf-class/pp202402#34]
안녕하세요, Assignment 3A 관련 질문 드립니다.
문제에서 주어지는 n의 값과 len 값의 조건이 궁금해서 질문 남기려고 합니다. 

문제 설명 가운데 다음과 같이 작성되어 있는 사항을 확인하였습니다.

> You don't need to worry about overflow in Long Type.

이 뜻을, 문제에 예시로 작성해주신 실행과정에서 수행하는 연산에 대해, LongType 범위에서 overflow가 나지 않도록 Input의 범위를 제한한다는 의미로 이해할 수 있을까요?

**Comment by Yeonwoo-Nam** [comment]
네. Long Type의 사칙연산 과정에서 overflow가 발생하지 않을 정도로만 len 값을 제한해서 채점할 예정입니다.
