### ISSUE TITLE
[Assignment 3B] Library function 및 data structure 사용 관련 질문

### ISSUE THREAD

**Issue by coinmoles** [snu-sf-class/pp202402#35]
안녕하세요.

Assignment 3B를 수행하던 중, 다른 과제에는 있었던 library function 및 data structure 사용 restriction 관련 사항이 없는 것을 확인했습니다. 
Assignment 3B에서는 이들을 사용해도 되는 걸까요?

감사합니다.

**Comment by haan6** [comment]
네, Assignment 3B 역시 이전 과제와 마찬가지로 라이브러리 함수와 데이터 구조의 사용이 불가하다는 점을 안내드립니다.
