### ISSUE TITLE
[Assignment 3B] 오목 테스트 코드 및 테스트 케이스 이상 사항

### ISSUE THREAD

**Issue by coinmoles** [snu-sf-class/pp202402#36]
안녕하세요, Assignment 3B를 수행하던 중 오목 테스트 코드 및 테스트 케이스에서 이상 사항이 발견되어 말씀드립니다.

아래는 제공된 `TestSuite.scala`의 `test_omok` 함수의 일부입니다.
```scala
def test_omok(test_file: String, arrayBuilder: ArrayBuilder): Unit = {
    ...

    val output = scala.io.Source.fromFile(f"$file_prefix/output/$test_file.txt").getLines().toList
    val outputTrimmed = output.filterNot(_.isEmpty)
    val answer = scala.io.Source.fromFile(f"$file_prefix/answer/$test_file.txt").getLines().toList
    val answerTrimmed = answer.filterNot(_.isEmpty)
}
```
그런데 이 함수에서 출력 파일과 답안 파일을 읽어온 후, 이 두 파일의 내용을 비교하는 부분이 없이 함수가 종료되어 출력 파일이 답안 파일과 일치하지 않더라도 테스트가 통과되는 것을 확인하였습니다.

또한, 제공된 첫 번째 테스트 케이스의 경우, 마지막에서 세 번째 줄의 move인 "0 4 X"가 놓인 후 이후 보드의 상황이 
```
O | O | O | X | X
-----------------
  | X | X | X | O
-----------------
O | O | X | X | O
-----------------
O | X | O | O |   
-----------------
X | O | X | X |   
```
와 같아져 X가 기울기 1인 대각선을 채워 승리하고, 게임이 종료되어야 합니다.
그런데 주어진 `answer/omok1.txt`에서는 이 "0 4 X" 이후 두 move까지 놓인 후, 결과로는 not done이 쓰여져 있습니다.

이 두 가지 확인 부탁드립니다. 감사합니다.

**Comment by haan6** [comment]
안녕하세요, 말씀해주신 사항을 확인하여 모든 학생의 `pp-assignment-3B` 레포의 `errata` 브랜치에 새로운 테스트 케이스와 테스트 코드를 추가하였습니다. 과제를 할 때 `errata` 브랜치의 내용을 `main` 브랜치에 반영하여주시길 바랍니다.
