### ISSUE TITLE
[Assignment 3B] board size 관련 질문드립니다.

### ISSUE THREAD

**Issue by jhy213** [snu-sf-class/pp202402#38]
omok의 경우에는 board의 크기가 5x5, sudoku는 9x9로 명시되어있는데, 채점할 때에도 board크기가 5x5, 9x9로 정해져 있다고 생각하고 구현하면 될지 질문드립니다.

**Comment by haan6** [comment]
네 채점할 때 board의 size는 omok의 경우 5x5, sudoku는 9x9로 고정한 테스트 케이스를 사용할 예정입니다.
