### ISSUE TITLE
[Assignment 3B] `GameController` 관련 질문

### ISSUE THREAD

**Issue by Prown0** [snu-sf-class/pp202402#41]
Assignment 3B의 `GameController` 관련하여 질문이 있어서 글을 올립니다.

1. `GameController`의 `state`는 유효하다고 가정할 수 있나요? 주어진 코드에서는 생성할 때 유효하지 않은 인자로 `GameController` 인스턴스를 생성하는 것을 막지 않는 것으로 보이는데, 이런 경우를 대비해서 `makeMove`에서 주어진 `GameController`의 `state`가 유효한지도 확인해야 하는지 궁금합니다.
2. 수 자체는 유효하지만 착수한 직후의 `state`는 유효하지 않은 경우는 유효하지 않은 수로 간주하여야 하나요? 오목의 경우에는 확실히 그렇게 하여야 할 것 같지만, 스도쿠의 경우에는 플레이어가 같은 가로줄, 세로줄, 작은 정사각형 내 중복된 수를 넣지 못하도록 애초부터 막아야 하는지가 확실하지 않아 질문 드립니다.

읽어 주셔서 감사합니다!

**Comment by haan6** [comment]
1. `GameController`를 생성할 때 유효하지 않은 state의 따로 막지는 않지만, `makeMove`에서 현재 state가 게임 규칙에 맞는지 확인하고, 입력받은 사용자의 수가 적절한지 검사한 후 새로운 `GameController`를 만드시면 됩니다.

2. 스도쿠에서는 애초에 중복된 수를 넣지 못하도록 처리하시면 됩니다. 채점할 때는, 중복된 수가 들어간 보드가 아닌 이전의 보드 상태를 확인할 예정입니다.

ex) 다음의 보드 상태에서 (1, 3)에 5를 넣는 수가 입력으로 들어올 경우
```
1 2 3 | 4 5 6 | 0 0 0
4 5 6 | 0 0 0 | 0 0 0
...
```
`failed` 문구와 함께 (1, 3)에 5를 적지 못한 보드가 반환되도록 코드를 작성하시면 됩니다.
```
failed
1 2 3 | 4 5 6 | 0 0 0
4 5 6 | 0 0 0 | 0 0 0
...
```

**Comment by Prown0** [comment]
추가적인 질문이 있습니다.

현재 `SimpleArrayBuilder`, `StrangeArrayBuilder`가 `MyArray`의 `update` 함수를 부작용이 있는 방식으로 구현하다 보니, 이를 부르기만 하여도 기존 `MyArray` 인스턴스가 바뀝니다. 이렇듯 `MyArray`의 실제 구현이 임의의 부작용이 있을 수 있음을 감안하고 과제를 구현하여야 할까요?

**Comment by haan6** [comment]
네 감안하여 코드를 작성해주시면 됩니다.

**Comment by Prown0** [comment]
답변 감사합니다!
