### ISSUE TITLE
[Assignment 3] 오버라이딩 질문

### ISSUE THREAD

**Issue by Prown0** [snu-sf-class/pp202402#42]
다른 주제로 질문이 생겨 이렇게 글을 쓰게 되었습니다.

이번 과제에서 오버라이딩을 사용하여도 괜찮을까요?

딱히 어디에 적혀 있는 것 같지는 않지만, 본 과목에서 오버라이딩을 좋지 않은 기능으로 배웠기에 질문 드립니다.

**Comment by haan6** [comment]
네, 오버라이딩을 사용하셔도 괜찮지만 권장하고 있지는 않습니다.

**Comment by Prown0** [comment]
네, 감사합니다!
