### ISSUE TITLE
[Assignment 4B] task uncompleted case 질문드립니다.

### ISSUE THREAD

**Issue by caelum02** [snu-sf-class/pp202402#47]
Assignment4B의 과제 스펙에, 구현해야하는 processTask 함수가 task 가 process 후 끝나지 않았을 때, 다시 enqueue해야 한다고 안내되어있습니다.

    *   - If a task is not completed, meaning, if a process method returns `IOption.ISome(newTask)`,
    *     it should be enqueued again to the corresponding priority queue.
    
현재 과제에서 주어진 Data.scala 파일을 확인했을 때, Task.process의 return type은 Optional이 아닌 I 그 자체이기 때문에 스펙에서 처럼 IOption.ISome(newTask)가 리턴되는 일이 없을 것 같은데 어떻게 처리하면 좋을지 질문드립니다.

**Comment by haan6** [comment]
`IOption.ISome(newTask)`가 아닌 `Task.process`가 return하는 `newTask`의 priority가 `IOption.ISome(_)`인 경우로 생각해주시면 되겠습니다.

관련 내용을 `errata` 브랜치에 추가하였습니다.
