### ISSUE TITLE
Assignment #1 (Due date: 2024/10/13 23:59:59 KST)

### ISSUE THREAD

**Issue by Yeonwoo-Nam** [snu-sf-class/pp202402#5]
Assignment #1 has been released. Solve the problems and submit your answers just as you did for Assignment #0.  Due date is 2024/10/13 23:59:59 KST. Please check the README.md file in the repository for more information about the assignment. If you have questions, Ask questions in [Issues](https://github.com/snu-sf-class/pp202402/issues).

**Comment by Yoseph-J** [comment]
안녕하세요 조교님, 컴퓨터공학부 23학번 정요셉입니다. Assignment 내용이 이메일에 보이지 않습니다. 확인해주시면 감사하겠습니다. 
Emai: cookie11123@snu.ac.kr

**Comment by Yeonwoo-Nam** [comment]
For problem 3-1, we will grade only for input value at most `9142446473643264109L` , which is a provided test case.
We are sorry for the late annoucement.
See https://github.com/snu-sf-class/pp202402/issues/10 for details.
