### ISSUE TITLE
[Assignment 0b] .gitignore 요청

### ISSUE THREAD

**Issue by kreatinj** [snu-sf-class/pp202402#55]
안녕하세요

Assignment 0b 과제에 프로젝트 초기화가 되어있지 않은 것으로 보여 `cargo init` 명령어를 실행해야 하는 것 같습니다.
`cargo init` 명령어에 의해 `target` 폴더가 생성되는데 `.gitignore` 파일에 해당 경로를 추가해주실 수 있으실까요?
또한, `cargo init`을 생략할 수 있도록 `Cargo.toml` 파일과 `Cargo.lock` 파일이 프로젝트에 추가되어도 좋겠습니다.

**Comment by Yeonwoo-Nam** [comment]
`.gitignore` 파일 작성 시 있었던 오류를 수정했습니다. errta 브랜치의 내용을 머지하시면 `cargo init` 명령어를 생략해도 cargo 명령어들을 사용할 수 있습니다. target 폴더는 `.gitignore` 파일에 이미 들어가 있습니다. 감사합니다.

**Comment by kreatinj** [comment]
`target` 폴더는 이미 안에 있군요. `cargo init` 명령어가 `target` 경로를 추가해서 착각했습니다
