### ISSUE TITLE
[Final Exam] Lecture note supply 관련 질문드립니다.

### ISSUE THREAD

**Issue by gs18113** [snu-sf-class/pp202402#58]
안녕하세요, final exam announcement의 Range 항목 관련해서 질문드립니다.
Lecture note and Rust document will be provided except for excercises. 라는 문구가 있는데, lecture note 외에도 별도의 rust 관련 문서가 제공되는 것일까요?

**Comment by Yeonwoo-Nam** [comment]
project에 주석으로 달려 있는 rust doc 링크와 마찬가지로, 
시험에서도 해당 문제에서 사용 가능한 라이브러리의 document의 링크가 주석으로 제공될 예정입니다. 
예 : https://doc.rust-lang.org/std/rc/struct.Rc.html

**Comment by gs18113** [comment]
감사합니다!
