### ISSUE TITLE
[Project] 사용가능 기능 질문

### ISSUE THREAD

**Issue by jhy213** [snu-sf-class/pp202402#59]
project를 구현 할 때, for, while과 같은 반복문을 사용해도 되는지 질문드립니다.

**Comment by haan6** [comment]
for, while 문을 사용하셔도 괜찮습니다. 관련 문법은 https://doc.rust-lang.org/std/keyword.for.html나 https://doc.rust-lang.org/std/keyword.while.html를 참고하시면 될 것 같습니다.

**Comment by jhy213** [comment]
감사합니다.
