### ISSUE TITLE
[Project] letfun관련 질문

### ISSUE THREAD

**Issue by kohandy1902** [snu-sf-class/pp202402#60]
Duplicate names cannot be defined within the esame scope.

문제에 다음과 같이 같은 이름의 변수나 함수가 같은 범위에 정의될 수 없다고 되어있는데, 이같은 입력이 주어지지 않는 것인지, 주어졌을 때 panic을 띄워야 하는지 궁금합니다.

감사합니다.

**Comment by Yeonwoo-Nam** [comment]
ill-typed inputs(사칙연산이나 if0의 condition에 closure가 들어간다거나, integer value에 function application을 한다거나 등)을 제외한 나머지 조건들 (하나의 letfun에서 동일한 이름의 함수 여러개를 정의할 수 없다, name은 숫자로 시작해서는 안되며 alphanumeric해야 한다)은 입력이 그렇게 주어지지 않는다는 뜻으로, panic을 띄우시지 않아도 됩니다.
