### ISSUE TITLE
[Project] Identifier 이름 검사용 추가 메소드 사용 질문

### ISSUE THREAD

**Issue by coinmoles** [snu-sf-class/pp202402#61]
안녕하세요.

과제를 수행하던 중, 

> Identifiers (names) x must be alphanumeric and cannot start with a digit.

의 조건을 검사하기 위해 명시된 메소드들 외에도 추가로 메소드를 사용하면 편리할 것 같아, 사용 가능 여부를 질문드립니다.

아래 메소드들을 사용해도 괜찮을까요?
- `str::is_empty`
- `str::chars`
- `char::is_alphanumeric`
- `char::is_numeric`

감사합니다.

**Comment by haan6** [comment]
안녕하세요, 말씀하신 str, char 관련 메소드를 사용하셔도 괜찮습니다.

**Comment by caelum02** [comment]
#60 을 확인했을 때에는 그러한 입력이 주어지지 않는 다는 것 같습니다
