### ISSUE TITLE
[Project] Memoization에서 VNum -> VClo 함수에 적용 여부

### ISSUE THREAD

**Issue by kwonlauren** [snu-sf-class/pp202402#63]
프로젝트 문서에는 아래와 같이 argument가 number인 경우에 memoization을 한다고 나와있습니다.
For function applications in memoized functions, if the argument evaluates to a number, check if the computation result is already recorded in M.
스켈레톤코드에서 Memo 는 HashMap<i64, i64> 라서 argument, result가 모두 i64인 함수들만 결과를 저장할 수 있는 것 같습니다.
argument가 숫자이고 반환값이 Closure인 경우에는 memoization을 해야 하나요?

**Comment by Yeonwoo-Nam** [comment]
argument와 return value 모두가 number인 경우에만 memoization을 하시면 되는 것이 맞습니다. 
문서에 해당 내용이 빠진 것 같습니다. 죄송합니다.
