### ISSUE TITLE
[Project] .clone() 사용 여부

### ISSUE THREAD

**Issue by limlimlim00** [snu-sf-class/pp202402#64]
구현되어 있는 struct나 enum에 대하여 .clone() 메서드를 사용해도 되는지 여쭤보고 싶습니다.

**Comment by Yeonwoo-Nam** [comment]
struct나 enum 정의 상단에 `#[derive Clone]`이 적혀있는 경우에는 clone method가 존재하기 때문에 사용하실 수 있지만, 그렇지 않은 경우에는 컴파일 되지 않기 때문에 사용하실 수 없습니다.

**Comment by limlimlim00** [comment]
감사합니다.
