### ISSUE TITLE
Assignment #1 추가조건에 대한 문의

### ISSUE THREAD

**Issue by crescmoon** [snu-sf-class/pp202402#7]
안녕하세요, 수업 수강하고 있는 컴퓨터공학부 23학번 문성빈입니다.

Assignment #1의 구현에 Library data structure의 사용에 제한이 있는데, 다음과 같은 구현을 해서는 안 되는 것인지 확인차 문의드립니다.

- `combination`이나 `isPrime` 등의 구현상 결과는 `Long`이나 직전 계산에서 오버플로우가 발생할 것으로 예상되는 경우(예: `Long`과 `Long`을 곱하고 `Long`으로 다시 나누는 경우)에 `BigInt` 연산을 하고 다시 `Long`으로 변환하는 것
- 잘못된 입력(예: `combination(4, 8)` 등)을 `throw new IllegalArgumentException("Invalid input")`처럼 처리하는 것

또한, `???`로 표기된 영역 바깥에서 구현하는 것은 자유롭게 가능한지 문의드립니다. 예를 들어,
```
def helperFunction() = ...
def isPrime(p: Long): Boolean = ???
```
처럼 `???` 영역 바깥에서 helper function을 구현해도 되는지, 아니면
```
def isPrime(p: Long): Boolean =
  def helperFunction() = ...
  ...
```
처럼 구현의 영역이 엄격하게 `???` 영역 안으로 제한되어 있는 것인지 궁금합니다.

**Comment by Yeonwoo-Nam** [comment]
1. 사전에 명시된 대로, 말씀하신 Library data structure은 사용하실 수 없습니다. 
1-1.  Problem 3-3처럼 문제에서 특별히 명시한 경우가 아니라면, `combination(4, 8)` 등 잘못된 입력은 채점용 testcase에 포함되지 않습니다. 
2. `???`로 표기된 영역 바깥에 helper function을 작성하는 것은 허용됩니다. (물론 `???` 영역에만 작성해도 통과할 수 있도록 출제했습니다. ) 다만  `src/main/scala/Main.scala` 파일에 작성된 내용만 채점에 반영됩니다.

**Comment by crescmoon** [comment]
네 답변 감사드립니다!
