### ISSUE TITLE
Assignment #1의 Execution Time에 관한 질문

### ISSUE THREAD

**Issue by hometogo4ever** [snu-sf-class/pp202402#9]
안녕하세요 조교님. 2023-15725 컴퓨터공학부 곽민서입니다. 테스트를 진행하는데, 실행시간이 벌써 20분을 넘겼는데, 보통 소요되는 실행시간이 어느정도 인지 여쭙고 싶습니다. timeout이라고 하기엔 timeout은 error로 판단한다고 되어있어, 애매하여 질문드렸습니다.

**Comment by Yeonwoo-Nam** [comment]
실제 채점시에는 문제나 testcase에 따라 시간제한이 다를 수 있으나, 제공된 testcase 1개(`test("problem ?") { ... }`로 묶인 부분)의 실행에 30초가 넘지 않도록 작성하셔야 합니다.
